name: Go

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go 1.22.x
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.0'
    - name: Go version check 
      run: go version
    - name: Install dependencies
      run: go mod download    
    - name: Build
      run: go build -v ./...
    - name: Test
      run: |
        branch_name=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')
        go test -coverprofile=coverage.out -v ./... -json > TestResults.json
    - name: Upload Go test results
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: Go-test-results
        path: TestResults.json
    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: Go coverage report
        path: coverage.out
  deploy-to-dev:
    if: github.event_name == 'create' && github.event.ref_type == 'tag' && contains(github.ref, 'refs/tags/master')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev
        run: echo "Deploying to Dev environment...with terraform"
