# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
    branches: [ "master" ]

jobs:
  build:
    runs-on: golang:1.22-alpine
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
